version: '3.3'
volumes:
  db-vol:
services:
  db:
    container_name: db
    build: ./db
    volumes:
      - db-vol:/var/lib/mysql
    ports:
      - '3306:3306'
  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8002:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=500000000
  api:
    container_name: api
    build: ./api
    ports:
      - '8001:80'
    volumes:
      - ../api:/var/www/html
